# Generated by Django 2.1.3 on 2018-11-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentphoto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postphoto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
