# Generated by Django 2.1.3 on 2018-11-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_feed', '0002_auto_20181129_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='postphoto',
            name='name',
            field=models.CharField(default='no name', max_length=250),
            preserve_default=False,
        ),
    ]
