# Generated by Django 2.1.3 on 2018-11-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_feed', '0003_postphoto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
